services:
  database:
    image: docker.io/library/mariadb:latest
    container_name: minecraft_db
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'minecraft_user'
      MYSQL_PASSWORD: '456'
    volumes:
      - ./db_data:/var/lib/mysql
  velocity:
    build:
      context: .
      dockerfile: Dockerfiles/velocity.Dockerfile
    container_name: velocity_proxy
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 0.5G
    ports:
      - "0.0.0.0:25565:25565/tcp"
    volumes:
      - ./server/velocity:/data
      - ./scripts/entrypoint_velocity.sh:/entrypoint_velocity.sh
    restart: unless-stopped
  smp:
    build:
      context: .
      dockerfile: Dockerfiles/smp.Dockerfile
    container_name: smp_server
    stdin_open: true # -i
    tty: true # -t
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 3G
    volumes:
      # Server files (your tree server/smp folder)
      - ./server/smp:/data
      # Shared plugins and configs
      - ./shared/plugins:/shared/plugins:ro
      - ./shared/configs:/shared/configs
      # Script to Docker
      - ./scripts/entrypoint_smp.sh:/entrypoint_smp.sh
    environment:
      - eula=TRUE
    restart: unless-stopped
    ports:
      - "0.0.0.0:25561:25565/tcp"
      - "0.0.0.0:8123:8123/tcp"

  # Other servers (lobby, towny) can be added in the same way.