root:
  tabprefix: "&4[#] &croot&f: "
  tagprefix: "&4root &8| &f"
sudoers:
  tabprefix: "&6[%] &e@sudo&f: "
  tagprefix: "&6sudo &8| &f"
wheel:
  tabprefix: "&b[!] &3wheel&f: "
  tagprefix: "&3wheel &8| &f"
chmod+x:
  tabprefix: "&a[x] &2chmod&f: "
  tagprefix: "&2chmod &8| &f"
users:
  tabprefix: "&7[$] &fuser&f: "
  tagprefix: "&7user &8| &f"
guest:
  tabprefix: "&8[?] &8guest&f: "
  tagprefix: "&8guest &8| &f"
_DEFAULT_:
  tabprefix: "&8[?] &8guest&f: "
