root:
  tabprefix: "<#91628d>&l[#] <#c294bc>&lROOT <#91628d>» &f"
  tagprefix: "<#91628d>ROOT &8| &f"
sudoers:
  tabprefix: "<#a2759d>&l[%] <#b387ad>&lSUDO <#a2759d>» &f"
  tagprefix: "<#a2759d>SUDO &8| &f"
wheel:
  tabprefix: "<#b387ad>&l[!] <#c294bc>&lWHEEL <#b387ad>» &f"
  tagprefix: "<#b387ad>WHEEL &8| &f"
chmod+x:
  tabprefix: "<#c294bc>&l[x] <#d3a5cd>&lCHMOD <#c294bc>» &f"
  tagprefix: "<#c294bc>CHMOD &8| &f"
users:
  tabprefix: "&7[$] <#a0a0a0>USER &8» &f"
  tagprefix: "&7USER &8| &f"
guest:
  tabprefix: "&8[?] &8GUEST &8» &7"
  tagprefix: "&8GUEST &8| &7"
_DEFAULT_:
  tabprefix: "&8[?] &8GUEST &8» &7"